version: '2.2'

services:
  ambari:
    image: danielrodriguez/docker-ambari-server
    hostname: ambari
    container_name: ambari
    cpu_shares: 100
    mem_limit: 2000000000
    ports:
      - "8080:8080"
#    volumes:
#      - /tmp/ambari/run:/var/run/ambari-server
#      - /tmp/ambari/log:/var/log/ambari-server
    networks:
      ambarinet:
        ipv4_address: 10.1.0.10

  namenode:
    image: danielrodriguez/docker-ambari-agent
    hostname: namenode
    container_name: namenode
    cpu_shares: 100
    mem_limit: 2000000000
    ports:
      - "50070:50070"
    privileged: false
    networks:
      ambarinet:
        ipv4_address: 10.1.0.11

  resourcemanager:
    image: danielrodriguez/docker-ambari-agent
    hostname: resourcemanager
    container_name: resourcemanager
    cpu_shares: 100
    mem_limit: 2000000000
    ports:
      - "8088:8088"
      - "19888:19888"
    privileged: false
    networks:
      ambarinet:
        ipv4_address: 10.1.0.12

  master:
    image: danielrodriguez/docker-ambari-agent
    hostname: master
    container_name: master
    cpu_shares: 100
    mem_limit: 2000000000
    ports:
      - "3000:3000"
    privileged: false
    networks:
      ambarinet:
        ipv4_address: 10.1.0.13

  node1:
    image: danielrodriguez/docker-ambari-agent
    hostname: node1
    container_name: node1
    cpu_shares: 100
    mem_limit: 2000000000
    privileged: false
    networks:
      ambarinet:
        ipv4_address: 10.1.0.14


  node2:
    image: danielrodriguez/docker-ambari-agent
    hostname: node2
    container_name: node2
    cpu_shares: 100
    mem_limit: 2000000000
    privileged: false
    networks:
      ambarinet:
        ipv4_address: 10.1.0.15

  node3:
    image: danielrodriguez/docker-ambari-agent
    hostname: node3
    container_name: node3
    cpu_shares: 100
    mem_limit: 2000000000
    privileged: false
    networks:
      ambarinet:
        ipv4_address: 10.1.0.16

networks:
  ambarinet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24
        gateway: 10.1.0.1
